apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-agent
  template:
    metadata:
      labels:
        app: delivery-agent
    spec:
      containers:
        - name: delivery-agent
          image: Akash-github1/delivery-agent:latest
          ports:
            - containerPort: 8084

---
apiVersion: v1
kind: Service
metadata:
  name: delivery-agent
spec:
  type: ClusterIP
  ports:
    - port: 8084
      targetPort: 8084
  selector:
    app: delivery-agent