apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
spec:
  replicas: 0
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
        - name: service-registry
          image: Akash-github1/service-registry:latest
          ports:
            - containerPort: 8761  # Update to your application's port

---
apiVersion: v1
kind: Service
metadata:
  name: service-registry
spec:
  type: ClusterIP
  ports:
    - port: 8761          # Change to match your application's port
      targetPort: 8761    # Ensure the targetPort matches your application
  selector:
    app: service-registry