apiVersion: apps/v1
kind: Deployment
metadata:
  name: end-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: end-user
  template:
    metadata:
      labels:
        app: end-user
    spec:
      containers:
        - name: end-user
          image: Akash-github1/end-user:latest
          ports:
            - containerPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  name: end-user
spec:
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: end-user